[package]
name = "self-modify"
version = "0.1.0"
authors = ["Laurențiu Nicola <lnicola@dend.ro>"]
edition = "2018"

[profile.release]
panic = "abort"

[dependencies]
byteorder = "1.3"
goblin = "0.0.22"
memmap = "0.7"
